### ISSUE TITLE
Support for Reolink Argus PT2

### ISSUE THREAD

**Issue by eumb** [thirtythreeforty/neolink#82] opened 2020-10-13 11:45 UTC
I have a battery-powered Argus PT2 which does not support either RTSP or HTTP. From the network scan tests performed, no TCP ports are opened on this camera. 
Connection using the Reolink client is possible only by using the UID with user and pass. While sniffing the traffic I only see UDP connection to an IP address I do not recognize.

Could there be a possibility to support also this camera?

Thank you

**Comment by QuantumEntangledAndy** [comment] 2020-10-13 12:15
I believe this issue is fundamentally a Duplicate of #30. 

Neolink currently supports TCP connections only. Not because we don't want to support UDP but because none of the developers have a UDP camera for us to reverse engineer.

If your tech savvy you can help us add this capability. The first step would be a wireshark packet capture.

**Comment by thirtythreeforty** [comment] 2020-10-13 15:43
Actually - @jlg89 has generously sent me an Argus cam, so I do have ~victim~ sample hardware! I have yet to really begin looking at the UDP protocol though, due to lack of time. The protocol analyzer improvements in #80 will help with this.

In the meantime, I think I'm going to close this as a duplicate of #30.

**Closed by thirtythreeforty** 2020-10-13 15:43 UTC
Labels: enhancement
