### ISSUE TITLE
Update broken binary links in readme

### ISSUE THREAD

**Issue by spacebares** [thirtythreeforty/neolink#329] opened 2022-12-09 18:23 UTC
Binary links for ubuntu, macos, and windows are broken. They seem to have changed filenames according to:

https://nightly.link/thirtythreeforty/neolink/workflows/build/master

**Comment by QuantumEntangledAndy** [comment] 2022-12-14 07:48
Duplicate of #328

@thirtythreeforty will have to fix the links since he has control of those nightly URLs in the mean time you can check [here](https://github.com/thirtythreeforty/neolink/actions/runs/3616506691)

**Closed by QuantumEntangledAndy** 2022-12-14 07:48 UTC
Labels: bug
