### ISSUE TITLE
Support B500 ip camera? 

### ISSUE THREAD

**Issue by sajtos888** [thirtythreeforty/neolink#230] opened 2021-11-20 15:34 UTC
Hi! 

I have B500 cameras. MainStream does not work no image connected to rtsp stream but no image. subStream, on the other hand, has an image.
Is there a solution for this or isn't this camera supported?

I'm running in Docker:
   Caused by:

        0: Media Deserialization error

        1: Parsing error

[2021-11-20T15:22:07Z INFO  neolink::rtsp] test: Connecting to camera at Address: x.x.x.x:9000

[2021-11-20T15:22:07Z INFO  neolink::rtsp] test: Logging in

[2021-11-20T15:22:07Z INFO  neolink::rtsp] test: Connected and logged in

[2021-11-20T15:22:07Z INFO  neolink::rtsp] test: Camera time is already set: 2021-11-20 16:25:36 +1

[2021-11-20T15:22:07Z INFO  neolink::rtsp] test: Camera reports firmware version v3.0.0.108_20092314

[2021-11-20T15:22:07Z INFO  neolink::rtsp] test: Starting video stream Main Stream (Clear)

config:

 bind = "0.0.0.0"
 
 [[cameras]]
 name = "test"
 username = "user"
 password = "xxxx"
 address = "x.x.x.x:9000"
 stream = "subStream"
 format = "H264"

Thank you very much for your reply!

**Comment by QuantumEntangledAndy** [comment] 2021-11-21 02:37
I believe that this is a possible duplicate of #226 and #225, there seems to be something in these cameras that is causing the bcmedia to fail to deserialise. I want to work on this but I will be too buzy working on the dayjob for the next month for me to really give it the attention it needs. :(

**Comment by QuantumEntangledAndy** [comment] 2021-11-27 11:02
I've been working with the data provided in #218 and have perhaps found the source of issue as discussed in #237.

Could you test this [build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/1509932254) and report back with whatever errors you have. If it does fail then a wireshark dump would be very useful.

**Comment by sajtos888** [comment] 2021-11-27 15:10
I took the resolution back and used this docker image "quantumentangledandy/neolink: newer_enc" and so the stream has been running for a long time!  :)

**Comment by QuantumEntangledAndy** [comment] 2021-11-27 23:57
Hmmm I'm surprised that it wasn't already working then because newer_enc has already been merged into master. I wonder what was up

**Comment by sajtos888** [comment] 2021-11-28 00:04
Unfortunately I don't know but if I set the resolution to max then I only see the vlc logo in vlc and nothing happens if I take the resolution back then the stream starts and works stably.  But I will also test the new build if I have time for it. 

Thanks!

**Comment by QuantumEntangledAndy** [comment] 2021-12-05 03:44
I am not sure if you are still having issues or not, but in case you are we have had progress with the error in #226 and have an updated build that should get it working [here](https://github.com/QuantumEntangledAndy/neolink/actions/runs/1534694282). Alternatively you can use our docker build 

```bash
docker pull quantumentangledandy/neolink:argus2_media
```

**Comment by sajtos888** [comment] 2021-12-05 05:54
It seems to be going perfectly for days!
docker pull quantumentangledandy/neolink

**Closed** 2022-03-02 03:38 UTC
Labels: bug
