### ISSUE TITLE
Stopping a running Video?

### ISSUE THREAD

**Issue by weltmeyer** [thirtythreeforty/neolink#272] opened 2022-05-09 22:00 UTC
**Describe the bug**
Using the "api" i currently start a videostream via
cam .start_video(&mut ext_output, Stream::Main)
disconnecting the camera crashes the start_video loop

**To Reproduce**
Steps to reproduce the behavior. Example:
Let a camera run (BcCamera.start_video(...))
send a dbCamera.Disconnect()
crash :(

**Expected behavior**
Disconnect the Camera, dont crash in the camera loop

**Versions**
git master

**Comment by QuantumEntangledAndy** [comment] 2022-05-09 23:28
What exactly is your error message?

One of my branches adds a more graceful stopping method but it was never merged. 

If the error is caused by a dropped Chanel though you might want to consider some way of stopping your read of the channel prior to calling disconnect.

In another of my branch that used a lot of loops when I ended up doing was having a central syncronisation control object that could be used to signal that all loops should disconnect and stop then only after all of that fire the disconnect.

**Comment by weltmeyer** [comment] 2022-05-10 05:59
Background: I have never programmed in rust. I needed the raw frames in my app.  I dont want the route via rtsp :)

I am calling your api "reolin_core" from external Software und it works wonderful (Get Video/Audio Decoded via FFMPEG/libav)
My app is calling the  cam.startvideo method with a custom output via ffi.

My only problem currently is stopping the video as the .Disconnect command works but i get a "Memory Access Violation" from the thread the ".StartVideo" runs in.

the minimal example would be somethingh like(Sorry, still pseudocode as i am writing from my memory):

let cam=new bcCamera(...);
let outputs=outputstruct;
ca,m.login(...)
thread::start(|_|,{cam.startVideo(outputs);}
thread:sleep(duration::from_millis(5000));
cam.disconnect()

**Comment by QuantumEntangledAndy** [comment] 2022-05-10 07:14
I see. Disconnect is just send the please hang-up message to the camera. Which means that it won't get more frames and the video will timeout waiting for it. 

You should just be able to handle the error message and clean up though. Why is it panicking?

**Comment by QuantumEntangledAndy** [comment] 2022-05-10 07:16
How is your rust? Maybe you can make a simple addition to core that will just pull a frame and quit.

**Comment by QuantumEntangledAndy** [comment] 2022-05-10 07:20
What happens if you just change it to this:

```rust

thread::start(|_|,{
	let _ = cam.startVideo(outputs);//throws error after calling cam.disconnect()
};
```

**Comment by QuantumEntangledAndy** [comment] 2022-05-10 07:24
Safe rust shouldn't get a memory access violation. Unless it's calling something in unsafe rust land like gstreamer or something. Are you sure your actual error isn't happening in the part of the code that handles the outputs.

**Comment by weltmeyer** [comment] 2022-05-10 18:08
I am coming close:
xDD
as i wrote.. i have no idea what i am doing in rust...

```
D:\SourceCodes\Alle\neolink-lib>target\debug\neolink_bin.exe
Start.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AddrResolutionError', src/main.rs:15:74
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
![image](https://user-images.githubusercontent.com/1668465/167694060-3afcf666-0608-4db4-bbb3-68c9bc664639.png)

I need to test with the references and pointers as i transfer the pointers to my app to later access the cam instance.

Gonna do some more trial.. at least.. this is a speaking error message :)

**Comment by weltmeyer** [comment] 2022-05-10 19:25
i got it finally working now. if you want, you can possibly add it to the core crate:

`pub use neolink_core::{
    bc_protocol::{StreamOutput, StreamOutputError},
    bcmedia::model::*,
};

use bc_protocol::BcCamera;
use neolink_core::bc_protocol::{self, Stream};

use std::convert::TryInto;
use std::ffi::CStr;
use std::os::raw::c_char;
use std::thread;

pub use bc_protocol::Error;

#[repr(C)]
pub enum FrameType {
    /// H264 video data
    H264 = 0,
    /// H265 video data
    H265 = 1,
    AAC = 2,
    AdPCM = 3,
}

pub struct ExtOutputs {
    //frametype
    //seconds since 1970
    //data pointer
    //data length
    pub frame_func: unsafe extern "C" fn(FrameType, u32, *mut u8, i32),
    pub info_func: unsafe extern "C" fn(u32, u32, u8), //widh,height,fps
}

impl StreamOutput for ExtOutputs {
    fn write(&mut self, media: BcMedia) -> StreamOutputError {
        let mut frame_type = FrameType::H264;
        //let mut dosend = false;

        let mut timestamp = 0;
        let mut payloaddata: Vec<u8> = Vec::new();
        match media {
            BcMedia::Iframe(payload) => {
                frame_type = match payload.video_type {
                    VideoType::H264 => FrameType::H264,
                    VideoType::H265 => FrameType::H265,
                };

                payloaddata = payload.data;
                timestamp = payload.time.unwrap_or(0);
            }
            BcMedia::Pframe(payload) => {
                frame_type = match payload.video_type {
                    VideoType::H264 => FrameType::H264,
                    VideoType::H265 => FrameType::H265,
                };
                payloaddata = payload.data;
            }
            BcMedia::Aac(payload) => {
                payloaddata = payload.data;
                frame_type = FrameType::AAC;
            }
            BcMedia::Adpcm(payload) => {
                payloaddata = payload.data;
                frame_type = FrameType::AdPCM;
            }
            BcMedia::InfoV1(payload) => {
                unsafe { (self.info_func)(payload.video_width, payload.video_height, payload.fps) };
                return Ok(());
            }
            BcMedia::InfoV2(payload) => {
                unsafe { (self.info_func)(payload.video_width, payload.video_height, payload.fps) };
                return Ok(());
            }

            _ => {
                //Ignore other BcMedia like InfoV1 and InfoV2
            }
        }

        if payloaddata.len() > 0 {
            let data_length = payloaddata.len().try_into().unwrap();
            let data_ptr = payloaddata.as_mut_ptr();
            unsafe {
                (self.frame_func)(frame_type, timestamp, data_ptr, data_length);
            }
        }

        Ok(())
    }
}

#[no_mangle]
pub extern "C" fn lib_test() {
    println!("Hello from the library!");
}

///opens a camera connection
#[no_mangle]
pub extern "C" fn lib_cam_open(
    c_ipaddress: *const c_char,
    c_username: *const c_char,
    c_password: *const c_char,
) -> *mut BcCamera {
    let ipaddress = string_from_c(c_ipaddress);
    let password = string_from_c(c_password);
    let username = string_from_c(c_username);
    println!("Hello from the library, host:{}!", ipaddress);
    let mut camera: BcCamera = BcCamera::new_with_addr(ipaddress, 0).unwrap();

    camera
        .login(&username, Some(&password))
        .map_err(|e| println!("error:{}!", e))
        .ok();

    return Box::into_raw(Box::new(camera));
}

///starts camera stream main
#[no_mangle]
pub extern "C" fn lib_cam_start_stream(
    ptr: *const BcCamera,
    newdata: unsafe extern "C" fn(FrameType, u32, *mut u8, i32),
    info: unsafe extern "C" fn(u32, u32, u8), //width,height,fps
) {
    let mut ext_output: ExtOutputs = ExtOutputs {
        frame_func: newdata,
        info_func: info,
    };

    let cam = unsafe {
        assert!(!ptr.is_null());
        &*ptr
    };

    thread::spawn(move || {
        cam.start_video(&mut ext_output, Stream::Main)
            .map_err(|e| println!("error:{}!", e))
            .ok();

        println!("Run finished.");
    });
}

#[no_mangle]
pub extern "C" fn lib_cam_stop(ptr: *mut BcCamera) {
    let cam = unsafe {
        assert!(!ptr.is_null());
        &mut *ptr
    };
    println!("Disconnecting!");
    cam.disconnect();

    println!("Disconnected!");
    println!("Unboxing!");
    unsafe {
        Box::from_raw(ptr);
    }

    println!("Unboxed!");
}

pub fn string_from_c(s: *const c_char) -> String {
    let c_str = unsafe {
        assert!(!s.is_null());

        CStr::from_ptr(s)
    };

    let r_str = c_str.to_str().unwrap();
    return r_str.to_string();
}
`


C# interfacing:

`  public static unsafe class neowrapper
    {
        const string dllPath = @"D:\SourceCodes\Alle\neolink-lib\target\debug\neolink_lib.dll";//@"D:\SourceCodes\Alle\neolink\target\debug\neolink_core.dll";

        public enum FrameType
        {
            /// H264 video data
            H264 = 0,
            /// H265 video data
            H265 = 1,
            AAC = 2,
            AdPCM = 3,
        }



        public delegate void newdata(FrameType frameType, UInt32 timestamp, byte* data, Int32 dataLength);
        public delegate void newinfo(UInt32 width, UInt32 height, ushort fps);

        [DllImport(dllPath, SetLastError = true, EntryPoint = "lib_cam_open")]

        //[return: MarshalAs(UnmanagedType.Bool)]
        public static extern void* lib_cam_open(string ipAddress, string username, string password);



        [DllImport(dllPath, SetLastError = true, EntryPoint = "lib_cam_start_stream")]
        public static extern void lib_cam_start_stream(void* instance, void* newdatavoid, void* newinfovoid);

        [DllImport(dllPath, SetLastError = true, EntryPoint = "lib_cam_stop")]
        public static extern void lib_cam_stop(void* instance);

    }`

**Comment by weltmeyer** [comment] 2022-05-10 19:28
Ok.. my new lib.rs: https://gist.github.com/weltmeyer/5a431f47c4de517c8fbe7e1cfe7acfb8
c# interfacing: https://gist.github.com/weltmeyer/181cd3b45429d1b5aebb3f15a189eae5

**Comment by weltmeyer** [comment] 2022-05-10 19:30
Example usage : (Reading Rawframe and creating ffmpeg avpacket)
![image](https://user-images.githubusercontent.com/1668465/167707381-6a4ae3bd-5b2f-4ac6-bf5c-a0a4eac1a7da.png)

**Comment by weltmeyer** [comment] 2022-05-10 20:23
Your project was exactly, what i was missing thank you very much..
i can also add, neolink is working for
RLC-810A 
and 
RLC-410-5MP

i had always a lot of artifacts using the cameras rtsp stream.. with neolink this is not the case!

![image](https://user-images.githubusercontent.com/1668465/167715430-dbbdb0fb-8a65-468a-9948-745861ae51c4.png)

**Closed** 2023-04-26 20:02 UTC
Labels: bug
